

	/**
	Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

		Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
		Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
		Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
		It can be verified that T285 = P165 = H143 = 40755.

		Find the next triangle number that is also pentagonal and hexagonal. **/
	

import java.util.Scanner;
public class TriPenHex {


	public static int Triangle(int n){
		n = n*(n+1) /2;
//		System.out.println("The next triangle is " + n);
		return n;
	}
	public static int Pentagon(int n){
		n = n*(3*n - 1)/2;
//		System.out.println("The next Pentagon is " + n);
		return n;
	}
	public static int Hexagon(int n){
		n = n * (2*n-1);
		return n;
	}



	public static void main(String[] args){



		for(int i = 285; i < 200000; i++)
		{
			for(int j = 165; j < 200000; j++){
				if(Triangle(i)==Pentagon(j)){
					for(int k = 143; k < 20000; k++){
						if(Triangle(i) == Hexagon(k)){
							System.out.println("Triangle " + i + " Pentagon " + j + " Hexagon " + k);
						}
					}
				}
			}
		}
		System.out.println("Fin");
	}
}